neo4j:
    image: neo4j
    ports:
      - "7474:7474"
# postgres:
#     image: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./postgresql/:/docker-entrypoint-initdb.d
#     environment:
#       - POSTGRES_PASSWORD=!n@n!m!nd_p0stgr3s
mail:
    image: tvial/docker-mailserver
    hostname: mail
    domainname: inanimind.com
    # your FQDN will be 'mail.inanimind.com'
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./spamassassin:/tmp/spamassassin/
      - ./postfix:/tmp/postfix/
# bonita:
#     image: bonita
#     ports:
#       - "8080:8080"
#     links:
#       - postgres
#     volumes:
#       - ./bonita:/opt/bonita
#     environment:
#       - TENANT_LOGIN=inanimind
#       - TENANT_PASSWORD=inanimindBONITA
#       - PLATFORM_LOGIN=pfadmin
#       - PLATFORM_PASSWORD=pfsecret
bundle-intrisk-api:
    build: ./../intrisk-api
    volumes:
      - /bundle
ruby-intrisk-api:
    build: ./../intrisk-api
    ports:
      - "3002:9292"
    links:
      - neo4j
      - mail
    volumes:
      - ./../intrisk-api:/app
    volumes_from:
      - bundle-intrisk-api
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - BUNDLE_PATH=/bundle
    command: bash -c "cd /app && rm -f /app/tmp/pids/server.pid && gem install grape-entity && bundle install && rubocop && rspec -c -P spec/**/*_spec.rb && shotgun --server=thin --port=9292 --host=0.0.0.0"
#bundle-intrisk-web:
#    build: ./../intrisk-angular2
#    volumes:
#      - /bundle
#angular2-intrisk-web:
#    build: ./../intrisk-angular2
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./../intrisk-angular2:/project/app
#    links:
#      - ruby-intrisk-api
